angler: QCamera: remove the last unused parameters
device/huawei/angler/camera/QCamera2/HAL3/QCamera3Channel.cpp:778:61:
error: unused parameter 'isType' [-Werror,-Wunused-parameter]
int32_t QCamera3ProcessingChannel::initialize(cam_is_type_t isType)
                                                            ^
device/huawei/angler/camera/QCamera2/HAL3/QCamera3Channel.cpp:1196:28:
error: unused parameter 'metadata' [-Werror,-Wunused-parameter]
        metadata_buffer_t *metadata,
                           ^
device/huawei/angler/camera/QCamera2/HAL3/QCamera3Channel.cpp:2168:65:
error: unused parameter 'stream' [-Werror,-Wunused-parameter]
                                                QCamera3Stream *stream)

Change-Id: Iaf464752051bcc782ae90e61db4308c41ef025d3