angler: QCamera: remove unused parameter for handleBatchMetadata
device/huawei/angler/camera/QCamera2/HAL3/QCamera3HWI.cpp:2313:51:
error: unused parameter 'free_and_bufdone_meta_buf'
[-Werror,-Wunused-parameter]
        mm_camera_super_buf_t *metadata_buf, bool
free_and_bufdone_meta_buf)

Change-Id: I5e86ff6262ea5e5fc40840e9ea1565e2a296ddb2