angler: QCamera: remove unused labels
device/huawei/angler/camera/QCamera2/HAL3/QCamera3PostProc.cpp:365:1:
error: unused label 'on_error' [-Werror,-Wunused-label]
on_error:
^~~~~~~~~

device/huawei/angler/camera/QCamera2/HAL3/QCamera3HWI.cpp:2456:1: error:
unused label 'done_batch_metadata' [-Werror,-Wunused-label]
done_batch_metadata:
^~~~~~~~~~~~~~~~~~~~

Change-Id: Iffb4bef315123f9448ef68535e19d5b406d9ca2f