angler: QCamera: remove unused parameter from registerBuffer
device/huawei/angler/camera/QCamera2/HAL/QCameraMem.cpp:981:59: error:
unused parameter 'bufType' [-Werror,-Wunused-parameter]
        cam_stream_type_t streamType, cam_stream_buf_type bufType)

device/huawei/angler/camera/QCamera2/HAL3/QCamera3Mem.cpp:738:27: error:
unused parameter 'type' [-Werror,-Wunused-parameter]
        cam_stream_type_t type)

        --> LEADS TO

device/huawei/angler/camera/QCamera2/HAL3/QCamera3StreamMem.cpp:287:24:
error: too many arguments to function call, expected 1, have 2; did you
mean 'gralloc_module_t::registerBuffer'?
    return mGrallocMem.registerBuffer(buffer, type);

Change-Id: Iebcb83fc0bbdd9816a1a0d1378a09436bd3753f3